### ISSUE TITLE
doubts

### ISSUE THREAD

**Issue by thextrem23** [ZebraNorth/vrchat-taur-tutorial#1]
in number 21(unity). Shall we also delete the rear hips with the rear legs? or do we delete everything that says textuall?

in number 23 (unity). create follow target in both or create the head and hips in different armadur

**Comment by ZebraNorth** [comment]
Hi, sorry for not replying to this earlier, I did not see any notification for it.

In Unity #21, yes delete the rear hips, rear legs, everything past Spine 1.
In Unity #23, your "Rear Hips" will have two new children.  There is only one "Rear Hips", as you deleted one in step #21.

Hope that helps.  Unfortunately I do not recommend this tutorial any more as it is for the version 2 SDK, and new avatars should use the version 3 SDK.  The methods should still work though.
